export const author = {
  name: `Smartoire Solutions Inc.`,
  nickname: `Smartoire`,
  seo: {
    title: "Smartoire Solutions Inc. - Cloud Solutions & Services",
    description: `Provide innovative cloud solutions and services for modern businesses.`,
    keywords: [
      "Software Developer",
      "Dynamics 365",
      "Power Platform",
      "Data Engineering",
      "Canada",
      "British Columbia",
      "Smartoire Solutions Inc.",
    ],
  },
  contact: {
    email: "hello@smartoire.com",
    phone: "+1 (778) 508-8833",
    address: "117 - 223 15th St E, North Vancouver, BC V7L 2P7, Canada",
    location: "Vancouver, BC, Canada",
    country: "Canada",
    url: "https://smartoire.com",
    calendly: "https://calendly.com/smartoire/",
  },
  social: {
    siteUrl: `https://smartoire.com`,
    facebook: `https://www.facebook.com/smartoire`,
    X: `https://x.com/smartoire`,
    linkedin: `https://www.linkedin.com/company/smartoire/`,
    youtube: `https://www.youtube.com/@cloudoire`,
    github: `https://github.com/Smartoire/`,
    instagram: `https://www.instagram.com/smartoireinc/`,
  },
  skills: [
    "C#",
    "ASP.NET Core",
    "Entity Framework",
    "SQL Server",
    "C++",
    "Python",
    "Java",
    "Spring Boot",
    "Hibernate",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Docker",
    "MongoDB",
    "SQL Server",
    "MySQL",
    "PostgreSQL",
    "Docker",
  ],
  certificates: [
    {
      code: "AZ-305",
      title: "Microsoft Certified: Azure Solutions Architect Expert",
    },
    {
      code: "SAA-C03",
      title: "AWS Certified Solutions Architect – Associate",
    },
    {
      code: "AZ-104",
      title: "Microsoft Certified: Azure Administrator Associate",
    },
    {
      code: "DP-100",
      title: "Microsoft Certified: Azure Data Scientist Associate",
    },
    {
      code: "DP-900",
      title: "Microsoft Certified: Azure Data Fundamentals",
    },
    {
      code: "AI-900",
      title: "Microsoft Certified: Azure AI Fundamentals",
    },
    { code: "AZ-900", title: "Microsoft Certified: Azure Fundamentals" },
    {
      code: "PL-900",
      title: "Microsoft Certified: Power Platform Fundamentals",
    },
    {
      code: "DP-300",
      title: "Microsoft Certified: Azure Database Administrator Associate",
    },
    {
      code: "DP-600",
      title: "Microsoft Certified: Azure Data Engineer Associate",
    },
    {
      code: "DP-420",
      title: "Microsoft Certified: Azure Cosmos DB Developer Specialty",
    },
  ],
  partners: [
    {
      name: "Cloudflare",
      url: "https://www.cloudflare.com/",
      logo: "/partners/cloudflare-logo.png",
      location: "San Francisco, CA, USA",
    },
    {
      name: "DigitalOcean",
      url: "https://www.digitalocean.com/",
      logo: "/partners/digitalocean-logo.png",
      location: "New York, NY, USA",
    },
    {
      name: "Microsoft",
      url: "https://www.microsoft.com/",
      logo: "/partners/microsoft-logo.png",
      location: "Redmond, WA, USA",
    },
    {
      name: "Amazon Web Services",
      url: "https://aws.amazon.com/",
      logo: "/partners/aws-logo.png",
      location: "Seattle, WA, USA",
    },
    {
      name: "Google Cloud",
      url: "https://cloud.google.com/",
      logo: "/partners/google-cloud-logo.png",
      location: "Mountain View, CA, USA",
    },
    {
      name: "MoneyWay",
      url: "https://moneyway.ca/",
      logo: "/partners/moneyway-logo.png",
      location: "North Vancouver, BC, Canada",
    },
  ],
};
